### ISSUE TITLE
Doesn't work for objects that are not active

### ISSUE THREAD

**Issue by mjholtzem** [jackisgames/TextMeshProReplacer#1]
Currently converting all text in scene uses
`Object.FindObjectsOfType<Text>()` 
which only finds active objects. It would be nice if this would also work on non-active objects, perhaps by using 
`Resources.FindObjectsOfTypeAll<Text>()`

**Comment by jackisgames** [comment]
Hey I think Resources.FindObjectsOfTypeAll might be bit dangerous because it can return prefabs from asset folder as well, but it's doable I'll do the fix soon.

**Comment by jackisgames** [comment]
Issue has been fixed
